CREATE SEQUENCE IF NOT EXISTS users_SEQ          START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS projects_SEQ       START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS project_members_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS columns_SEQ        START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS cards_SEQ          START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS attachments_SEQ    START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS notifications_SEQ  START WITH 1 INCREMENT BY 50;
