# ── Datasource ────────────────────────────────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

%dev.quarkus.datasource.username=kanban
%dev.quarkus.datasource.password=kanban123
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kanbandb

# ── Hibernate ─────────────────────────────────────────────────────────────────
quarkus.hibernate-orm.schema-management.strategy=none
%dev.quarkus.hibernate-orm.log.sql=true

# ── Flyway ────────────────────────────────────────────────────────────────────
quarkus.flyway.migrate-at-start=true

# ── JWT ───────────────────────────────────────────────────────────────────────
mp.jwt.verify.issuer=https://kanbanapp.com
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# ── Azure Blob Storage ────────────────────────────────────────────────────────
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=sprj-kanban-attachments

%dev.azure.storage.connection-string=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tiqIU1s+VJoqggJkb==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
